Insumos:
  path_insumos: "Insumos/"
  universo_directa:
    nom_base:  "Universo Directa.xlsm"
  universo_indirecta:
    nom_base: "Universo Indirecta.xlsm"
  base_socios:
    nom_base: "BaseSocios.xlsm"
  drv_cordenadas:
    nom_base: "base"

dict_columnas:
  cod_cliente : "Cód. Cliente"
