Insumos:
  path_insumos: 'Insumos/'
  universo_directa:
    nom_base: 'Universo Directa.xlsm'
    sheet: "Maestra"
  universo_indirecta:
    nom_base: 'Universo Indirecta.xlsm'
    sheet: "BD"
    concatenar_cols : 
      cols : ["r_id_agente_comercial", "r_id_cliente"]
      nueva_columna : "llave_compuesta"
      usar_separador : True
      separador : "_"
  Path_Directa:
    path: 'Directa/'
    patron: '.xlsx'
  Path_Indirecta:
    path: 'Indirecta/'
    sheet: 'Base' 
  base_socios:
    nom_base: 'BaseSocios.xlsm'
    sheet: 'Consolidado'
    
    columnas_socios_merge:
      atencion: "Atención"
      tip_socios:  "Tipo Socios"   # Columnas necesarias para el merge entre base socios y universos.
      cod_ven:  "Cod_vend Z1"
      nom_vend_z1:    "Nom_Vend Z1"
      cod_vend_z1: "Cod_vend ZA"
      nom_vend_za: "Nom_Vend ZA"
      
  
  drv_coordenadas:
    nom_base: 'DriverCoordenadas.xlsx'
    sheet: 'Base'
    concatenar_cols : 
      cols : ["Código ECOM", "Agente Comercial"]
      nueva_columna : "llave_compuesta"
      usar_separador : True
      separador : "_"


outputs: 
  indirecta_xlsx: "Resultados/Universo_Indirecta_Resultado.xlsx"
  directa_xlsx: "Resultados/Universo_Directa_Resultado.xlsx"
  indirecta_csv: "Resultados/Universo_Indirecta_Resultado.csv"
  directa_csv: "Resultados/Universo_Directa_Resultado.csv"
  directa_vts_csv: "Resultados/Ventas_Universo_Directa.csv"
  indirecta_vts_csv: "Resultados/Ventas_Universo_Indirecta.csv"


dict_cols:
    universo_directa:
      funcion_inter: "Función Inter."
      sociedad: "Sociedad"
      id_cliente: "Cód. Cliente"
      cod_local: "Cód. Loc."
      razon_social: "Razon_Social"
      nombre_cliente: "Nombre Cliente"
      nif: "N.I.F."
      poblacion: "Población"
      

    base_socios:
      id_cliente: "Cod_Cliente"
      atencion: "Atención"
      tipo_socio: "Tipo Socios"
      cod_jefe: "Cod_Jefe"
      nom_jefe: "Nom_Jefe"
      cod_agente: "Cod_Agente"
      nom_agente: "Nom_Agente"
      cod_vendedor: "Cod_vend ZA"


    universo_indirecta:
      id_cliente: "r_id_cliente"
      nombre: "cv_nombre_completo_cliente"
      cod_agente: "r_id_agente_comercial"
      nom_agente: "cv_nombre_agente_comercial"
      cod_jefe: "Cod_jefe"
      nom_jefe: "Nombre_jefe"

    drv_coordenadas:
      cod_agen_comer: "Agente Comercial"
      llave_compuesta: "llave_compuesta"
      directa:
         id_cliente: "Cliente"
         Grado_latitud: "Grado latitud"
         Grado_longitud: "Grad.long."
      indirecta:
        cod_ECOM: "Código ECOM"
        cod_agen_comer: "Agente Comercial"
        Grado_latitud: "Grado latitud"
        Grado_longitud: "Grad.long."


    columnas_socios_merge:
      atencion: "Atención"
      tip_socios:  "Tipo Socios"
      cod_ven:  "Cod_vend Z1"
      nom_vend_z1:    "Nom_Vend Z1"
      cod_vend_z1: "Cod_vend ZA"
      nom_vend_za: "Nom_Vend ZA"

    df_socios:
      col_socio: "Col_Socio"
      id_cliente: "Cód. Cliente"
    
    df_u_directa_completa_Socios:
      id_cliente: 'Cód. Cliente'

    df_u_indirecta:
      cod_agente: 'r_id_agente_comercial'
      id_cliente: 'r_id_cliente'


    df_ventas_directa:
      id_cliente: 'Cliente'

    df_ventas_indirecta:
      cod_ECOM: "Código ECOM"
      cod_agente: "Agente Comercial"
      






      

  
